version: "3.7"

services:
  api-laravel-boleto:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: trezzuri/api-laravel-boleto
    container_name: api-laravel-boleto
    ports:
      - mode: ingress
        target: 80
        published: "${APP_PORT:-80}"
        protocol: tcp
    volumes:
      - type: volume
        source: storage
        target: /var/www/html/storage
    networks:
      - net

  mongodb:
    image: mongo:7-jammy
    container_name: api-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
    networks:
      - net

volumes:
  storage:
  mongodb:

networks:
  net:
