version: "3.7"

services:
  api-cnab-boleto:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: xpendi/cnab-boleto
    container_name: api-cnab-boleto
    ports:
      - mode: ingress
        target: 80
        published: "${APP_PORT:-8080}"
        protocol: tcp
      - mode: ingress
        target: 443
        published: "${APP_PORT:-443}"
        protocol: tcp
    volumes:
      - "./:/var/www/html"
    networks:
      - net

  mongodb:
    image: mongo:7-jammy
    container_name: api-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
    networks:
      - net

volumes:
  mongodb:

networks:
  net:
