version: "3.7"

services:
  api-cnab-boleto:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: xpendi/cnab-boleto
    container_name: api-cnab-boleto
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./:/var/www/html"
    networks:
      - net

  mongodb:
    image: mongo:7-jammy
    container_name: api-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
    networks:
      - net

volumes:
  mongodb:

networks:
  net:
