version: "3.7"

services:
  api-laravel-boleto:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: trezzuri/api-laravel-boleto
    container_name: api-laravel-boleto
    ports:
      - mode: ingress
        target: 80
        published: "${APP_PORT:-8900}"
        protocol: tcp
    volumes:
      - type: volume
        source: storage
        target: /var/www/html/storage

volumes:
  storage: