version: "3.7"

services:
  cnab-boleto:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: xpendi/cnab-boleto
    container_name: api-cnab-boleto
    ports:
      - mode: ingress
        target: 80
        published: "${APP_PORT:-8080}"
        protocol: tcp
    volumes:
      - type: volume
        source: storage
        target: /var/www/html/storage
      - type: volume
        source: app
        target: /var/www/html/app
    networks:
      - net

  mongodb:
    image: mongo:7-jammy
    container_name: api-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
    networks:
      - net

volumes:
  app:
  storage:
  mongodb:

networks:
  net:
