#!/bin/sh

# Defina as variáveis de ambiente
COMMON_NAME="cnab.apis.xpendi.com.br"
COMMON_EMAIL="contato@xpendi.com.br"
# DAYS=365
# CERT_DIR="/cert"

# Crie o diretório se não existir
mkdir -p /etc/nginx/ssl/

rm -rp /etc/letsencrypt/archive/*
rm -rp /etc/letsencrypt/live/*
rm -rp /etc/nginx/ssl/*

nginx -s stop

# Execute o Certbot para obter e configurar o certificado SSL
certbot certonly --standalone -d $COMMON_NAME --non-interactive --agree-tos --force-renewal --email $COMMON_EMAIL

ln -s /etc/letsencrypt/live/$COMMON_NAME /etc/letsencrypt/live/default

cp /etc/letsencrypt/live/$COMMON_NAME/fullchain.pem /etc/ssl/certs/default.crt
cp /etc/letsencrypt/live/$COMMON_NAME/privkey.pem /etc/ssl/private/default.key

cp /etc/letsencrypt/live/$COMMON_NAME/fullchain.pem /etc/nginx/ssl/cert.pem
cp /etc/letsencrypt/live/$COMMON_NAME/privkey.pem /etc/nginx/ssl/key.pem

nginx -s reload