#!/bin/sh

# Defina as variáveis de ambiente
COMMON_NAME="cnab.apis.xpendi.com.br"
DAYS=365
CERT_DIR="/cert"

# Crie o diretório se não existir
mkdir -p $CERT_DIR

# Gere a chave privada
openssl genrsa -out $CERT_DIR/key.pem 2048

# Gere o certificado assinado pela chave privada
openssl req -new -x509 -key $CERT_DIR/key.pem -out $CERT_DIR/cert.pem -days $DAYS -subj "/CN=$COMMON_NAME"

# Copie os certificados SSL para o contêiner NGINX
cp /cert/key.pem /etc/nginx/ssl/
cp /cert/cert.pem /etc/nginx/ssl/